// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// CPP_exact_extract
Rcpp::List CPP_exact_extract(const Rcpp::NumericVector& extent, const Rcpp::NumericVector& res, const Rcpp::RawVector& wkb);
RcppExport SEXP _exactextractr_CPP_exact_extract(SEXP extentSEXP, SEXP resSEXP, SEXP wkbSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type extent(extentSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type res(resSEXP);
    Rcpp::traits::input_parameter< const Rcpp::RawVector& >::type wkb(wkbSEXP);
    rcpp_result_gen = Rcpp::wrap(CPP_exact_extract(extent, res, wkb));
    return rcpp_result_gen;
END_RCPP
}
// CPP_coverage_fraction
Rcpp::NumericMatrix CPP_coverage_fraction(const Rcpp::NumericVector& extent, const Rcpp::NumericVector& res, const Rcpp::RawVector& wkb);
RcppExport SEXP _exactextractr_CPP_coverage_fraction(SEXP extentSEXP, SEXP resSEXP, SEXP wkbSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type extent(extentSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type res(resSEXP);
    Rcpp::traits::input_parameter< const Rcpp::RawVector& >::type wkb(wkbSEXP);
    rcpp_result_gen = Rcpp::wrap(CPP_coverage_fraction(extent, res, wkb));
    return rcpp_result_gen;
END_RCPP
}
// CPP_stats
SEXP CPP_stats(Rcpp::S4& rast, const Rcpp::RawVector& wkb, const Rcpp::StringVector& stats);
RcppExport SEXP _exactextractr_CPP_stats(SEXP rastSEXP, SEXP wkbSEXP, SEXP statsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4& >::type rast(rastSEXP);
    Rcpp::traits::input_parameter< const Rcpp::RawVector& >::type wkb(wkbSEXP);
    Rcpp::traits::input_parameter< const Rcpp::StringVector& >::type stats(statsSEXP);
    rcpp_result_gen = Rcpp::wrap(CPP_stats(rast, wkb, stats));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_exactextractr_CPP_exact_extract", (DL_FUNC) &_exactextractr_CPP_exact_extract, 3},
    {"_exactextractr_CPP_coverage_fraction", (DL_FUNC) &_exactextractr_CPP_coverage_fraction, 3},
    {"_exactextractr_CPP_stats", (DL_FUNC) &_exactextractr_CPP_stats, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_exactextractr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
