// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// CPP_exact_extract
Rcpp::List CPP_exact_extract(const Rcpp::NumericVector& extent, const Rcpp::NumericVector& res, const Rcpp::RawVector& wkb);
RcppExport SEXP _exactextractr_CPP_exact_extract(SEXP extentSEXP, SEXP resSEXP, SEXP wkbSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type extent(extentSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type res(resSEXP);
    Rcpp::traits::input_parameter< const Rcpp::RawVector& >::type wkb(wkbSEXP);
    rcpp_result_gen = Rcpp::wrap(CPP_exact_extract(extent, res, wkb));
    return rcpp_result_gen;
END_RCPP
}
// CPP_stat
double CPP_stat(const Rcpp::NumericVector& extent, const Rcpp::NumericVector& res, const Rcpp::NumericMatrix& rast_values, const std::string& stat, const Rcpp::RawVector& wkb);
RcppExport SEXP _exactextractr_CPP_stat(SEXP extentSEXP, SEXP resSEXP, SEXP rast_valuesSEXP, SEXP statSEXP, SEXP wkbSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type extent(extentSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type res(resSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type rast_values(rast_valuesSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type stat(statSEXP);
    Rcpp::traits::input_parameter< const Rcpp::RawVector& >::type wkb(wkbSEXP);
    rcpp_result_gen = Rcpp::wrap(CPP_stat(extent, res, rast_values, stat, wkb));
    return rcpp_result_gen;
END_RCPP
}
// CPP_weights
Rcpp::NumericMatrix CPP_weights(const Rcpp::NumericVector& extent, const Rcpp::NumericVector& res, const Rcpp::RawVector& wkb);
RcppExport SEXP _exactextractr_CPP_weights(SEXP extentSEXP, SEXP resSEXP, SEXP wkbSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type extent(extentSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type res(resSEXP);
    Rcpp::traits::input_parameter< const Rcpp::RawVector& >::type wkb(wkbSEXP);
    rcpp_result_gen = Rcpp::wrap(CPP_weights(extent, res, wkb));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_exactextractr_CPP_exact_extract", (DL_FUNC) &_exactextractr_CPP_exact_extract, 3},
    {"_exactextractr_CPP_stat", (DL_FUNC) &_exactextractr_CPP_stat, 5},
    {"_exactextractr_CPP_weights", (DL_FUNC) &_exactextractr_CPP_weights, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_exactextractr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
