# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CPP_exact_extract <- function(extent, res, wkb) {
    .Call('_exactextractr_CPP_exact_extract', PACKAGE = 'exactextractr', extent, res, wkb)
}

CPP_stat <- function(extent, res, rast_values, stat, wkb) {
    .Call('_exactextractr_CPP_stat', PACKAGE = 'exactextractr', extent, res, rast_values, stat, wkb)
}

CPP_weights <- function(extent, res, wkb) {
    .Call('_exactextractr_CPP_weights', PACKAGE = 'exactextractr', extent, res, wkb)
}

