# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CPP_exact_extract <- function(extent, res, wkb) {
    .Call('_exactextractr_CPP_exact_extract', PACKAGE = 'exactextractr', extent, res, wkb)
}

CPP_coverage_fraction <- function(extent, res, wkb) {
    .Call('_exactextractr_CPP_coverage_fraction', PACKAGE = 'exactextractr', extent, res, wkb)
}

CPP_stats <- function(rast, wkb, stats) {
    .Call('_exactextractr_CPP_stats', PACKAGE = 'exactextractr', rast, wkb, stats)
}

